exclude: [README.md, cmd-ruby-x64.lnk, cmd-ruby-x86.lnk, not.md, index-old.md]

collections:
  authors:
    output: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

plugins:
  - jemoji
